
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30s
    user: admin
    password: admin
  jms:
    pub-sub-domain: true
server:
  port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.yaspeed.demo716.entity
  mapper-locations: classpath:mapper/*.xml